import  express from "express"; 
import * as branchController from "./branchController.js";
import { auth } from "../../middleware/auth.middleware.js";
import { studentAuth } from "../../middleware/authstudent.js";
const routerBranch = express.Router();    
routerBranch.post("/createBranch",auth, branchController.createBranch);
routerBranch.get("/year/:yearId",studentAuth, branchController.getBranchesByYear); 
routerBranch.put("/:id", auth, branchController.updateBranch);
routerBranch.delete("/:id", auth, branchController.deleteBranch);
routerBranch.get("/yearId/year/:yearId/simple", auth, branchController.getBranchIdsAndNamesByYear);
routerBranch.get("/:id", auth, branchController.getBranchById);
export default routerBranch;